---
title: ''
author: ''
date: ''
output: 
  html_document:
    df_print: paged
    keep_md: true
  word_document:
    reference_docx: style.1.docx
---

```{r setup, include = FALSE}

  knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                        fig.width  = 5 * 1.67, fig.height = 5)

# load("scripts/models_dec_2019.RData")
  source("scripts/01_project.R") # Produces the model and data objects

  library(sjPlot)
  library(tidyverse)
  library(broom)
  library(knitr)
  library(flextable)

```



Table 1. Respondent characteristics

```{r table1_data}

  descript <- select(
    data,
    sequence, sex, age_screening, height_m, weight_kg_screen, bmi_screening, 
    sbpscreening, dbpscreening, smoking_ever, alcohol_consumption,
              physical_mins, tv_hours, sleep_hours, occupation,
              educationcategory) %>%
    mutate(sex = factor(sex, labels = c("Male", "Female")),
           smoking_ever = factor(smoking_ever, labels = c("No", "Yes")),
           alcohol_consumption = factor(alcohol_consumption, 
                                        labels = c("No", "Yes")),
           occupation = factor(occupation),
           educationcategory = factor(educationcategory))

```


```{r table1_describe_html, eval = knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"}

  data_frame(Variable       = tools::toTitleCase(gsub("_", " ", name.1(descript))),
             N              = n.miss(descript),
             "Mean SD"      = summary.1(descript),
             "Median [IQR]" = med.iqr(descript),
             "(Min, Max)"   = min.max(descript)) %>%
  flextable()
  
```

```{r table1_describe_word, eval = !knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"}

  data_frame(Variable       = tools::toTitleCase(gsub("_", " ", name.1(descript))),
             N              = n.miss(descript),
             "Mean SD"      = summary.1(descript),
             "Median [IQR]" = med.iqr(descript),
             "(Min, Max)"   = min.max(descript)) %>%
  kable()
  
```


